### PR TITLE
Added repeatCount functionality

### PR DESCRIPTION
**Pull request by KiLLeRRaT**
Started adding repeatCount functionality.

A few things to keep into account while I was building this.
 - Need to track undo and redo to do the correct amount of repeats. 
 - Supporting for a max command length of 6, gives you plenty of repeat opportunity.

Still a couple of things to iron out:
 - [ ] `5yy` doesn't work, because of the way that selectRow works.

Please let me know if you have any feedback.

### CODE REVIEW

**Comment by philc** [comment]
Hey @KiLLeRRaT, thanks for submitting. This approach looks pretty straightforward.

I haven't played with it, but based on the code the undo/redo treatment looks problematic: if the user repeats a command, then issues a different command, and hits undo twice, the first repeated command will not get undone in one chunk. This is because we only remember the repeat count for one command, and Sheets itself isn't aware of repeats.

Given that undo is just a passthrough to sheets, I think we just shouldn't handle smartly undoing repeat commands, for simplicity.

Also, there should be a cap on how many times we repeat a command, to avoid the user locking up their browser. E.g. 10, or 99.

**Comment by jparoz** [comment]
I'd be keen to pick this back up and incorporate the changes mentioned, if that's okay with everyone?

**Comment by KiLLeRRaT** [comment]
> I'd be keen to pick this back up and incorporate the changes mentioned, if that's okay with everyone?

That would be great.  I haven't time to do this anymore, but would welcome this change.

**Comment by jparoz** [comment]
I've just opened #39, which incorporates this commit, as well as the mentioned changes. Thanks @KiLLeRRaT!

**Comment by philc** [comment]
Closed in favor of #39.

**Pull request closed without merging**
